<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<title>Slim 3</title>
	<link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
	<style>
		body {
			margin: 50px 0 0 0;
			padding: 0;
			width: 100%;
			font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
			text-align: center;
			color: #aaa;
			font-size: 18px;
		}

		h1 {
			color: #719e40;
			letter-spacing: -3px;
			font-family: 'Lato', sans-serif;
			font-size: 40px;
			font-weight: 200;
			margin-bottom: 20px;
		}
		table {
			margin: auto;
		}
		table td {
			text-align: left;
		}
	</style>
</head>
<body>
<h1>Net Magazine Magic Link Demo</h1>

<section id="messages">
	<?php if ( isset( $message ) ) : ?>
		<p><?php echo $message; ?></p>
	<?php endif; ?>
</section>

<section id="errors">
	<?php if ( isset( $error ) ) : ?>
		<p><?php echo $error; ?></p>
	<?php endif; ?>
</section>

<section id="main">
	<h2>Welcome, <?php echo $fName . ' ' . $lName; ?>!</h2>
	<p>You'll only see this page if you're properly logged in.</p>
	<p><a href="/logout">Logout</a></p>
</section>
</body>
</html>